<a href="https://colab.research.google.com/github/miamte/deep-learning-practice/blob/main/04_multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초 실습

## List to Numpy Array

In [75]:
# numpy 라이브러리를 np라는 별칭으로 임포트합니다.
import numpy as np

In [76]:
# 2차원 리스트를 numpy 배열로 변환하여 'test' 변수에 저장합니다.
test = np.array([[1,2,3], [4,5,6]])
# 'test' 배열의 내용을 출력합니다.
test

array([[1, 2, 3],
       [4, 5, 6]])

### 문제1 : 아래 list 3개를 각각 행으로 갖는 배열을 생성하는 코드를 완성하고 배열의 크기를 print 하세요

In [77]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

# 세 개의 리스트를 행으로 갖는 numpy 배열을 생성합니다.
arr = np.array([list1, list2, list3])

# 생성된 배열을 출력합니다.
print(arr)
# 배열의 크기(shape)를 출력합니다. (행, 열)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## Reshape

In [78]:
# 0부터 15까지의 숫자를 포함하는 1차원 배열을 생성한 후, (4,4) 형태로 재구성합니다.
arr16 = np.array(list(range(16))).reshape((4,4))
# 재구성된 배열을 출력합니다.
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 문제2 : 0부터 15까지의 숫자를 원소로 갖는 배열을 아래의 형태로 만드는 코드를 작성해보세요

In [79]:
# arr16 배열을 (8, 2) 형태로 재구성하여 arr16_reshaped 변수에 저장합니다.
arr16_reshaped = arr16.reshape((8, 2))
# 재구성된 배열을 출력합니다.
print(arr16_reshaped)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


## 0 or 1 값 채우기

In [80]:
# 16개의 요소가 모두 1.0인 1차원 numpy 배열을 생성합니다.
filled_one = np.ones(16)
# 생성된 배열을 출력합니다.
filled_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
# 2행 5열의 모든 요소가 0.0인 numpy 배열을 생성합니다.
filled_zero = np.zeros((2,5))
# 생성된 배열을 출력합니다.
filled_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
# arr16 배열과 동일한 형태를 가지면서 모든 요소가 1인 배열을 생성합니다.
filled_like_arr16 = np.ones_like(arr16)
# 생성된 배열을 출력합니다.
filled_like_arr16

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 문제 3 : 아래 형태를 갖는 배열을 만드는 코드를 작성해보세요
- ones, zeros, reshape 사용
- 성공했으면 concatenate의 axis를 0으로 바꿔보고 어떤 동작을 하는지 적어보세요

In [83]:
# arr_with_one 배열 참고
# [[1., 1.],
# [1., 1.],
# [1., 1.],
# [1., 1.]]

# arr_with_zero 배열 참고
# [[0., 0.],
# [0., 0.],
# [0., 0.],
# [0., 0.]]

# arr_with_one_zero 배열 참고
# [[1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.]]

# 4x2 크기의 모든 요소가 1인 배열을 생성합니다.
arr_with_one = np.ones((4, 2))
# 4x2 크기의 모든 요소가 0인 배열을 생성합니다.
arr_with_zero = np.zeros((4, 2))
# arr_with_one과 arr_with_zero 배열을 수평(axis=1)으로 결합합니다.
arr_with_one_zero = np.concatenate((arr_with_one, arr_with_zero), axis=1) # 수평으로 배열 합치기
# 결합된 배열을 출력합니다.
arr_with_one_zero

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

## Broadcasting

In [84]:
# 25개의 요소가 1인 배열을 생성 후 (5,5) 형태로 재구성합니다.
bc = np.ones(25).reshape((5,5))
# bc 배열의 모든 요소에 5를 곱하고 1을 빼서 브로드캐스팅 연산을 수행합니다.
bc = bc * 5 - 1
# 결과를 출력합니다.
bc

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [85]:
# bc 배열의 모든 요소를 0으로 만든 후 3을 더해 모든 요소가 3인 배열을 생성합니다.
bc2 = bc * 0 + 3
# bc와 bc2 배열을 더합니다.
bc + bc2

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [86]:
# 1차원 리스트를 생성합니다.
one_dim_arr = [5, 5, 5, 5, 5]
# bc 배열과 one_dim_arr 리스트를 브로드캐스팅하여 더합니다.
new_bc = bc + one_dim_arr
# 결과를 출력합니다.
new_bc

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

## Slicing

In [87]:
# arr16 배열을 출력합니다.
print(arr16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [88]:
# arr16 배열의 3번째 행(인덱스 2)을 선택하여 출력합니다.
arr16[2]

array([ 8,  9, 10, 11])

In [89]:
# arr16 배열의 3번째 행(인덱스 2)의 모든 열을 선택하여 출력합니다.
arr16[2,:]

array([ 8,  9, 10, 11])

In [90]:
# arr16 배열의 모든 행에서 3번째 열(인덱스 2)을 선택하여 출력합니다.
arr16[:,2]

array([ 2,  6, 10, 14])

In [91]:
# arr16 배열의 첫 번째와 두 번째 행(인덱스 0부터 2 미만)을 선택하여 출력합니다.
print(arr16[0:2])
# arr16 배열의 첫 번째 행(인덱스 0)의 세 번째 요소(인덱스 2)를 선택하여 출력합니다.
print(arr16[0,2])

[[0 1 2 3]
 [4 5 6 7]]
2


In [92]:
# arr16 배열의 두 번째와 세 번째 행(인덱스 1부터 3 미만)을 선택하여 출력합니다.
arr16[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
# arr16 배열에서 첫 번째 열(인덱스 0)의 값이 5보다 작은 행들을 선택하여 출력합니다.
arr16[arr16[:,0]<5]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 문제 4 : 3번째 열에서(index=2) 10보다 크거나 같은 원소가 있는 행 전체를 담는 배열을 생성해보세요

In [94]:
# 결과
# [ 8,  9, 10, 11],
# [12, 13, 14, 15]]

# arr16 배열에서 세 번째 열(인덱스 2)의 값이 10보다 크거나 같은 행들을 선택하여 'test_arr' 변수에 저장합니다.
test_arr = arr16[arr16[:, 2] >= 10]
# 'test_arr' 배열을 출력합니다.
test_arr

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 평균(mean)

In [95]:
# 모든 요소가 1인 (10000, 100) 크기의 numpy 배열을 생성합니다.
target = np.ones((10000,100))
# target 배열의 형태(shape)를 출력합니다.
target.shape

(10000, 100)

In [96]:
# target 배열의 열(axis=0)을 기준으로 평균을 계산합니다.
mean = target.mean(axis=0)
# 계산된 평균 배열의 형태(shape)를 출력합니다.
print(mean.shape)
# 계산된 평균 배열을 출력합니다.
print(mean)

(100,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [97]:
# target 배열의 행(axis=1)을 기준으로 평균을 계산합니다.
mean = target.mean(axis=1)
# 계산된 평균 배열의 형태(shape)를 출력합니다.
print(mean.shape)
# 계산된 평균 배열을 출력합니다.
print(mean)

(10000,)
[1. 1. 1. ... 1. 1. 1.]


# 코드를 통해서 XOR 문제 해결하기

In [98]:
# XOR 문제를 해결하기 위한 가중치와 바이어스 값을 정의합니다.
w11 = np.array([-2, -2]) # 첫 번째 은닉층 뉴런의 가중치
w12 = np.array([2, 2])   # 두 번째 은닉층 뉴런의 가중치
w2 = np.array([1, 1])    # 출력층 뉴런의 가중치

b1 = 3 # 첫 번째 은닉층 뉴런의 바이어스
b2 = -1 # 두 번째 은닉층 뉴런의 바이어스
b3 = -1 # 출력층 뉴런의 바이어스

In [99]:
# 퍼셉트론 함수를 정의합니다.
# 입력 x, 가중치 w, 바이어스 b를 받아 활성화 함수를 적용한 결과를 반환합니다.
def MLP(x, w, b):
    # 가중치와 입력의 곱의 합에 바이어스를 더합니다.
    y = np.sum(w * x) + b

    # 활성화 함수 (계단 함수): y가 0보다 작거나 같으면 0, 그렇지 않으면 1을 반환합니다.
    if y <= 0:
        return 0
    else:
        return 1

In [100]:
# NAND 게이트 함수를 정의합니다. MLP 함수와 w11, b1을 사용합니다.
def NAND(x1,x2):
    return MLP(np.array([x1, x2]), w11, b1)

# OR 게이트 함수를 정의합니다. MLP 함수와 w12, b2를 사용합니다.
def OR(x1,x2):
    return MLP(np.array([x1, x2]), w12, b2)

# AND 게이트 함수를 정의합니다. MLP 함수와 w2, b3를 사용합니다.
def AND(x1,x2):
    return MLP(np.array([x1, x2]), w2, b3)

# XOR 게이트 함수를 정의합니다. NAND, OR, AND 게이트를 조합하여 구현합니다.
def XOR(x1,x2):
    # NAND 게이트와 OR 게이트의 출력을 AND 게이트의 입력으로 사용합니다.
    return AND(NAND(x1, x2),OR(x1,x2))

In [101]:
# XOR 게이트의 모든 가능한 입력 값에 대해 최종 값을 출력합니다.
for x in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    # XOR 함수를 호출하여 결과를 얻습니다.
    y = XOR(x[0], x[1])
    # 입력 값과 출력 값을 출력합니다.
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 0
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0


# Multi Perceptron Class 생성을 통해 해결하기

In [102]:
# XOR 문제를 해결하기 위한 다층 퍼셉트론(Multi-Layer Perceptron) 클래스를 정의합니다.
class SimpleMLP:
    def __init__(self):
        # 수동으로 설정한 가중치와 바이어스
        # 입력층에서 은닉층으로 가는 가중치 (x1, x2 -> n1, n2 계산)
        self.weights_input_hidden = np.array([[-2, 2], [-2, 2]])
        # 은닉층 뉴런들의 바이어스 (x1, x2 -> n1, n2)
        self.bias_hidden = np.array([3, -1])

        # 출력층: 1개의 뉴런
        # 은닉층에서 출력층으로 가는 가중치 (n1, n2 -> y)
        self.weights_hidden_output = np.array([1, 1])
        # 출력층 뉴런의 바이어스 (n1, n2 -> y)
        self.bias_output = -1

    # 순전파(forward) 메서드를 정의합니다.
    def forward(self, X):
        # 은닉층 계산:
        # 입력 X와 입력-은닉층 가중치를 내적하고 은닉층 바이어스를 더합니다.
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        # 은닉층의 활성화 함수 (계단 함수): 0보다 작거나 같으면 0, 아니면 1
        hidden_output = np.where(hidden_input <= 0, 0, 1)
        print(f"hidden_output : {hidden_input}")

        # 출력층 계산:
        # 은닉층 출력과 은닉-출력층 가중치를 내적하고 출력층 바이어스를 더합니다.
        final_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output
        # 출력층의 활성화 함수 (계단 함수): 0보다 작거나 같으면 0, 아니면 1
        final_output = np.where(final_input <= 0, 0, 1)
        print(f"final_output : {final_input}")

        # 최종 출력을 반환합니다.
        return final_output

In [103]:
# XOR 문제의 입력값(X)과 실제 출력값(y) 데이터셋을 정의합니다.
XOR_X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # 입력값
XOR_y = np.array([0, 1, 1, 0])  # XOR 출력값

In [73]:
# SimpleMLP 모델을 초기화합니다.
mlp = SimpleMLP()

In [74]:
# 정의된 XOR 입력값(XOR_X)에 대해 모델의 순전파를 실행하여 예측값을 얻습니다.
predictions = mlp.forward(XOR_X)
# 예측 결과를 출력합니다.
print(f"XOR 문제 예측 결과: {predictions}")

hidden_output : [[ 3 -1]
 [ 1  1]
 [ 1  1]
 [-1  3]]
final_output : [0 1 1 0]
XOR 문제 예측 결과: [0 1 1 0]


1. (1) NAND Gate 해당하는 W열 [-2,-2]
   (2) OR Gate 해당하는 W열 [2,2]
2. 다층 퍼셉트론은 딥러닝 기초 구조
  2.1.딥러닝에 가장 중요하게 결정하는 요소
  선 그래프
  2.2.딥러닝과 다른 점
  선형회귀는 답을 찾아가지만 다층 퍼셉트론은 값을 미리 넣어주고 시작한다